name: build-linux-docker
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive, lfs: true }

      - name: Build CI image (cacheable)
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.ci
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/bitdecentral-ci:latest

      - name: Run build inside container
        run: |
          docker run --rm -v $PWD:/work -w /work ghcr.io/${{ github.repository_owner }}/bitdecentral-ci:latest \
          bash -lc "./scripts/ci/configure.sh && ./scripts/ci/build.sh && ./scripts/ci/test.sh"
